Repository cloud-bulldozer/cpt-dashboard, pull requests merged in 2025-04, with the labels that each got.

#188 add functional e2e gui test
  .github/workflows/frontend-check.yaml
  backend/poetry.lock
  backend/pyproject.toml
  backend/scripts/start.sh
  backend/tests/db_seed.py
  backend/tests/e2e_backend.sh
  backend/tests/fixtures/search_db_snapshots/snapshot.tar.gz
  backend/tests/functional.containerfile
  backend/tests/functional/setup/ocp_opensearch.yml
  backend/tests/ocpperf_test.toml
  backend/tests/opensearch_ocp.sh
  frontend/.gitignore
  frontend/README.md
  frontend/cypress/e2e/ocp.cy.js
  frontend/e2e_frontend.containerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/molecules/MetaDataRow/index.jsx
  frontend/src/components/organisms/TableFilters/index.jsx
  frontend/src/components/organisms/TableLayout/index.jsx
Labels: documentation, enhancement, ci

#190 Update GitHub Actions to ubuntu-latest
  .github/workflows/build-push.yaml
  .github/workflows/frontend-check.yaml
  .github/workflows/poetry-check.yaml
  .github/workflows/release-build-push.yaml
Labels: ci

#192 Add Web Server to Deployment and CI
  .github/workflows/frontend-check.yaml
  backend/tests/e2e_backend.sh
  frontend/e2e_frontend.containerfile
  frontend/frontend.containerfile
  frontend/nginx.conf
  pod-compose.sh
Labels: enhancement, ci

#196 Add Component Test
  frontend/cypress.config.js
  frontend/cypress/component/table_cell.cy.jsx
  frontend/cypress/support/component-index.html
  frontend/cypress/support/component.js
  frontend/src/components/atoms/TableCell/index.jsx
Labels: enhancement

#198 add command for component test execution
  .github/workflows/frontend-check.yaml
  frontend/README.md
  frontend/package.json
Labels: documentation, ci

#203 add a unit test
  .github/workflows/frontend-check.yaml
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utils/__tests__/helper.test.js
  frontend/src/utils/helper.js
  frontend/vite.config.js
Labels: documentation, enhancement

#206 add component tests job
  .github/workflows/frontend-check.yaml
Labels: ci
